### ISSUE TITLE
Add inputs validation

### ISSUE THREAD

**Issue by jamesmawm** [jamesmawm/golang-user-microservice#20]
Currently duplicate usernames are allowed to be stored in DB when the `OnSignup()` method in `api.go` is called.
Kindly assist to validate that a username is in use, and throw an error if so. 
Update the response in `swagger.yml` too as you go along.

**Comment by kazukilapislazuli** [comment]
Can I work on it?

**Comment by minaorangina** [comment]
May I take this one?

**Comment by jamesmawm** [comment]
Sure!

**Comment by jamesmawm** [comment]
Thanks!
