### ISSUE TITLE
Update swagger.yml

### ISSUE THREAD

**Issue by jamesmawm** [jamesmawm/golang-user-microservice#3]
Enable the CRUD operations for users.
Content type for all requests and responses should be `application/json`.

Examples are:
Create a user: POST /users
Read a user: GET /users/{user-uuid}
Update a user: PUT /users/{user-uuid}
Delete a user: DELETE /users/{user-uuid}
Authenticating a user: POST /login, returns a JWT token

**Comment by karimelazzouni** [comment]
I have already started working on the user sign up (`POST /users) to support #8 , so I might as well complete this one 😊. 
@jamesmawm Please assign it to me. 
Since there isn't a data store setup with the service for now, I am going to temporarily use an in-memory hash map to store the user data.
