### ISSUE TITLE
Enable environment configuration

### ISSUE THREAD

**Issue by jamesmawm** [jamesmawm/golang-user-microservice#6]
Add environment-level settings to this project.
The module `github.com/kelseyhightower/envconfig` helps with this.

Suggested configs to go along:
- Port usage
- Database switching
- API context path.

**Comment by paymin** [comment]
hei @jamesmawm can i try solved this one?
would you consider using `https://github.com/spf13/viper` ?

**Comment by yeganeh666** [comment]
I solved this =)
can you add the "hacktoberfest" topic to your repository?

**Comment by jamesmawm** [comment]
Added. 
A new env parsing package is not really needed, but I'll merge this anyway, 
Thanks!

**Comment by jamesmawm** [comment]
@paymin that works too.

Keeping this issue open as I'm looking out for a simple solution to add just a few configs.
Examples are:
- Secret keys (string)
- Database IP or host name (string)
- Server port to bind (string, not int)
- Environment name (string)

**Comment by paymin** [comment]
@paymin ok. i'll try to create simplest solution

**Comment by jamesmawm** [comment]
Awesome, thank you!
